/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AnalyticsOptOutRouteImport } from './routes/analytics-opt-out'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaintingsSlugRouteImport } from './routes/paintings.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsOptOutRoute = AnalyticsOptOutRouteImport.update({
  id: '/analytics-opt-out',
  path: '/analytics-opt-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingsSlugRoute = PaintingsSlugRouteImport.update({
  id: '/paintings/$slug',
  path: '/paintings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics-opt-out': typeof AnalyticsOptOutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/paintings/$slug': typeof PaintingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics-opt-out': typeof AnalyticsOptOutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/paintings/$slug': typeof PaintingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics-opt-out': typeof AnalyticsOptOutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/paintings/$slug': typeof PaintingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics-opt-out'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/shop'
    | '/paintings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics-opt-out'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/shop'
    | '/paintings/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics-opt-out'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/shop'
    | '/paintings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsOptOutRoute: typeof AnalyticsOptOutRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ShopRoute: typeof ShopRoute
  PaintingsSlugRoute: typeof PaintingsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics-opt-out': {
      id: '/analytics-opt-out'
      path: '/analytics-opt-out'
      fullPath: '/analytics-opt-out'
      preLoaderRoute: typeof AnalyticsOptOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paintings/$slug': {
      id: '/paintings/$slug'
      path: '/paintings/$slug'
      fullPath: '/paintings/$slug'
      preLoaderRoute: typeof PaintingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsOptOutRoute: AnalyticsOptOutRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ShopRoute: ShopRoute,
  PaintingsSlugRoute: PaintingsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
